import json,sys,time
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
from browser_harness import setup,request,BROWSER
ROOT=Path(__file__).resolve().parents[1];EVIDENCE=ROOT/'evidence';EVIDENCE.mkdir(exist_ok=True)
checks=[];errors=[]
def check(name,condition=True):
    assert condition,name
    checks.append({'check':name,'passed':True})
def idle(page):
    page.wait_for_function('!localBusy && state && !state.busy')
    page.wait_for_timeout(150)
def send(page,sender,to,text):
    page.locator('#sender').select_option(sender)
    page.locator('#recipient').select_option(to)
    page.locator('#message-text').fill(text)
    page.locator('#send-message').click();idle(page)

request('/api/reset',{'method':'POST','headers':{'Content-Type':'application/json'},'body':json.dumps({'mode':'client-server','count':4,'delayMs':0})})
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path=BROWSER,args=['--no-sandbox'])
    page=setup(browser,1600,1100)
    page.on('pageerror',lambda e:errors.append(str(e)))
    idle(page)
    check('Dashboard renders all four endpoints',page.locator('.svg-node').count()==4)
    send(page,'A','B','Hello from NetScope!')
    check('UI unicast returns a real recipient ACK','1 / 1' in page.locator('#send-result').inner_text())
    send(page,'C','ALL','Group 01 broadcast: Dhruv, Manan and Armaan.')
    check('UI broadcast reaches all three other configured nodes','3 / 3' in page.locator('#send-result').inner_text())
    send(page,'D','A','नमस्ते 🌐 — UTF-8 verified over TCP.')
    check('Unicode delivery succeeds','1 / 1' in page.locator('#send-result').inner_text())
    page.locator('[data-tab="inbox"]').click()
    page.locator('#inbox-node').select_option('A')
    check('Inbox displays actual decoded Unicode payload','नमस्ते' in page.locator('#records-content').inner_text())
    page.locator('[data-tab="sockets"]').click()
    check('Socket inspector exposes real loopback addresses','127.0.0.1:' in page.locator('#records-content').inner_text())
    page.locator('[data-tab="messages"]').click()
    page.locator('#message-text').fill('Hello from NetScope!')
    page.screenshot(path=str(EVIDENCE/'01-client-server-ui.png'),full_page=True)
    page.locator('.lab-grid').screenshot(path=str(EVIDENCE/'01-client-server-lab.png'))
    page.locator('#hub-toggle').click();idle(page)
    send(page,'A','B','Testing the central point of failure.')
    check('Hub failure is visible as a failed UI delivery','Central server is offline' in page.locator('#send-result').inner_text())
    check('Hub failure shows zero reachable pairs',page.locator('#reachability').inner_text().startswith('0 / 6'))
    page.screenshot(path=str(EVIDENCE/'02-hub-failure-ui.png'),full_page=True)
    page.locator('#hub-toggle').click();idle(page)
    send(page,'A','B','The hub has recovered.')
    check('Hub recovery reconnects clients','1 / 1' in page.locator('#send-result').inner_text())
    page.locator('#mode-p2p').click();idle(page)
    check('P2P mode creates six mesh links',page.evaluate('state.stats.activeLinks')==6)
    page.locator('[data-toggle-node="D"]').click();idle(page)
    send(page,'A','B','The surviving peers stay connected.')
    check('Peer failure preserves unrelated A-to-B delivery','1 / 1' in page.locator('#send-result').inner_text())
    send(page,'A','D','Offline peers cannot receive a message.')
    check('Offline peer delivery fails visibly','Recipient is offline' in page.locator('#send-result').inner_text())
    send(page,'B','C','Direct peer-to-peer. No central relay.')
    page.locator('#message-text').fill('The surviving peers stay connected.')
    page.screenshot(path=str(EVIDENCE/'03-peer-failure-ui.png'),full_page=True)
    page.locator('.lab-grid').screenshot(path=str(EVIDENCE/'03-peer-failure-lab.png'))
    page.locator('[data-toggle-node="D"]').click();idle(page)
    send(page,'D','A','Peer D is back online.')
    check('Peer recovery restores bidirectional delivery','1 / 1' in page.locator('#send-result').inner_text())
    # Text must remain text, never script execution.
    send(page,'A','B','<img src=x onerror="window.__xss=true">')
    page.locator('[data-tab="inbox"]').click();page.locator('#inbox-node').select_option('B')
    check('HTML-like payload is escaped in both logs and inbox',not page.evaluate('Boolean(window.__xss)') and page.locator('#records-content img').count()==0)
    page.locator('#node-count').select_option('8');page.locator('#apply-config').click();idle(page)
    check('Configuration creates eight real peers and 28 links',page.evaluate('state.count===8 && state.stats.activeLinks===28'))
    page.locator('#node-count').select_option('4');page.locator('#teaching-delay').select_option('20');page.locator('#apply-config').click();idle(page)
    send(page,'A','B','Teaching delay is explicit.')
    check('Teaching delay is reflected in measured application RTT',page.evaluate('state.stats.meanRttMs>=30'))
    page.locator('#reset-network').click();check('Reset confirmation dialog is visible',page.locator('#reset-dialog').is_visible())
    page.locator('#cancel-reset').click();check('Cancel keeps the live session',page.evaluate('state.messages.length===1'))
    page.locator('#reset-network').click();page.locator('#confirm-reset').click();idle(page)
    check('Confirmed reset clears live message logs',page.evaluate('state.messages.length===0'))
    page.locator('[data-view="compare"]').click()
    page.locator('#view-compare').wait_for(state='visible')
    check('Compare navigation works',page.locator('#view-compare').is_visible())
    page.locator('#run-comparison').click();idle(page)
    check('Comparison shows both measured architectures',page.locator('.compare-card').count()==2)
    check('Benchmark uses zero teaching delay',page.evaluate('currentComparison.config.delayMs===0'))
    page.screenshot(path=str(EVIDENCE/'04-comparison-ui.png'),full_page=True)
    page.locator('.compare-cards').screenshot(path=str(EVIDENCE/'04-comparison-cards.png'))
    page.locator('[data-view="history"]').click();page.wait_for_selector('.history-card')
    check('Experiment is present in persisted history',page.locator('.history-card').count()>=1)
    page.locator('[data-history-open="0"]').click()
    page.locator('#view-compare').wait_for(state='visible')
    check('Saved experiment reopens in comparison view',page.locator('#view-compare').is_visible())
    page.locator('[data-view="guide"]').click()
    page.locator('#view-guide').wait_for(state='visible')
    check('Guide includes limitations and real implementation references',page.locator('.guide-card').count()==7)
    page.locator('[data-view="lab"]').click()
    page.locator('#view-lab').wait_for(state='visible')
    # Capture a healthy peer topology for presentation overview.
    page.locator('#teaching-delay').select_option('0');page.locator('#apply-config').click();idle(page)
    send(page,'A','B','Architecture changes. The message stays the same.')
    page.locator('[data-tab="messages"]').click()
    page.locator('.lab-grid').screenshot(path=str(EVIDENCE/'05-peer-to-peer-lab.png'))
    mobile=setup(browser,390,844)
    mobile.on('pageerror',lambda e:errors.append(str(e)))
    idle(mobile)
    check('Mobile layout has no horizontal document overflow',mobile.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
    mobile.screenshot(path=str(EVIDENCE/'06-mobile-ui.png'),full_page=True)
    for view in ['compare','history','guide']:
        mobile.locator(f'[data-view="{view}"]').click();mobile.wait_for_timeout(200)
        check(f'Mobile {view} view has no horizontal document overflow',mobile.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
    check('No JavaScript page errors during UI checks',len(errors)==0)
    browser.close()
report={'method':'Chromium UI tests using unmodified production HTML/CSS/JS and a local HTTP bridge to the actual Node/TCP engine. Direct browser URL navigation is restricted in the build environment. Native HTTP/SSE is separately covered by Node integration tests.','checks':checks,'passed':len(checks),'failed':0,'pageErrors':errors}
(EVIDENCE/'ui-test-report.json').write_text(json.dumps(report,indent=2))
print(json.dumps(report,indent=2))
